#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -d I II III IV V
bspc monitor DP2 -d 1 2 3 4 5

bspc config focused_border_color "#0d81d6"   # Green for focused windows
bspc config normal_border_color  "#45475A"   # Dark gray for normal windows
bspc config active_border_color  "#F38BA8"   # Red for active windows

bspc config top_padding 0
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Autostart applications
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
